### PR TITLE
Added refresh endpoint w/ token

### PR DESCRIPTION
**Pull request by joeherm**
- Add `/refresh?token=specified_token` endpoint that sends SIGHUP

### CODE REVIEW

**Comment by joeherm** [comment]
Apologies- meant to open this on our fork.

**Comment by brendan-ward** [comment]
@joeherm we're open to considering something like this in the base repo too; there was [some discussion](https://github.com/consbio/mbtileserver/pull/78#issuecomment-576407905) on the related filesystem-based reloader.  

However, using SIGHUP from an API endpoint feels a little awkward ("hey server please restart yourself").  Instead, I think I'd want to implement something that sets a mutex (so multiple calls to `/reload` in separate threads don't collide), then uses something similar to what we're doing [here](https://github.com/consbio/mbtileserver/pull/78#issuecomment-576407905) to rescan the registered directories and re-add those that exist.

This could also be extended to take a service ID and reload just that, which would likely be nice for certain cases too.

We didn't (yet) have those specific use cases, so I haven't put further thought into supporting a `reload` HTTP API.  One thing that we didn't work out was how to handle authentication for this:
* shared secret (your token); which is nice and lightweight but also risky, it could get logged as plaintext anywhere in between caller and `mbtileserver` and potentially used to do a DOS attack
* HTTP Basic Auth based on credentials provided at server startup
* something else?

**Comment by joeherm** [comment]
Apologies for the late response! I meant to respond earlier and it got a bit lost in the holiday shuffle. I agree with what you're saying here about the awkwardness of the having the server restart itself, though we did implement the above (with slight changes) as a workaround for our short-term needs.

If there is interest in having that merged happy to do so, otherwise perhaps I should file an issue? If I get some downtime it's something I would be happy to work on and contribute back :) .

**Comment by brendan-ward** [comment]
Added #133 for this idea

**Pull request closed without merging**
