### PR TITLE
Add WMTS support

### PR DESCRIPTION
**Pull request by reyemtm**
Issues

- Printing in AGOL
- Shift in AGOL

Fixes

- LOD not populating
- Tiles showing up in wrong place due to y shift

Adds

- Removed "Layers" from the MapServer endpoint

### CODE REVIEW

**Comment by brendan-ward** [comment]
@reyemtm thanks for working on this!

Since the substantive work here is around WMTS support, I'd like to extract out your early work in this PR and handle that specifically for ArcGIS and keep this PR oriented toward WMTS.  I'm going to work on the ArcGIS side of things now; apologies for my delay in getting going with this.

Note that in general, my preference here would be to stick close to the standard package `encoding/xml` and avoid bringing in new dependencies unless there is a clear win worth the extra deps.

**Comment by reyemtm** [comment]
Yeah sounds good. I'm fairly new to xml and GO for that matter so have
testing out some different ways to encode the necessary response. It seems
like it's doable with the native go libraries.

I heard back from Esri that the print issue with XYZ tiles is supposed to
be fixed in the next release of server/AGOL which is due out in winter
2021... we'll see.

**Comment by reyemtm** [comment]
On that PR, forgot to create a new branch for the WMTS testing so those got
mixed in there which I didn't intend to do. There weren't many changes to
fix the ArcGIS endpoint so you should be able to pull those out manually.

**Comment by reyemtm** [comment]
closed

**Pull request closed without merging**
