### PR TITLE
Refactor of handlers, middleware, command line options

### LINKED ISSUE #82: FR: allow optionally disable additional endpoints
https://github.com/consbio/mbtileserver/blob/10eb6193b711e9b007edb060721b61737de550a5/README.md#L18-L23
https://github.com/consbio/mbtileserver/blob/10eb6193b711e9b007edb060721b61737de550a5/README.md#L338-L341
It would be great to make it possible to optionally disable all additional stuff (TileJSON endpoint, map preview, etc). In production, I would like to expose only tile-level access. I think it's quite common case.

### PR DESCRIPTION
**Pull request by brendan-ward**
Resolves #82, #94.  Supersedes #99.  Progress toward #78.

# Overview
This version involved a significant refactor of internal functionality and HTTP
handlers to provide better ability to modify services at runtime, provide
granular control over the endpoints that are exposed, and cleanup handling
of middleware.

Most internal HTTP handlers for `ServiceSet` and `Tileset` in the
`github.com/consbio/mbtileserver/handlers` package are now `http.HandlerFunc`s
instead of custom handlers that returned status codes or errors as in the previous
versions.

The internal routing within these handlers has been modified to enable
tilesets to change at runtime. Previously, we were using an `http.ServeMux`
for all routes, which breaks when the `Tileset` instances pointed to by those
routes have changed at runtime. Now, the top-level `ServiceSet.Handler()`
allows dynamic routing to any `Tileset` instances currently published. Each
`Tileset` is now responsible for routing to its subpaths (e.g., tile endpoint).

The singular public handler endpoint is still an `http.Handler` instance but
no longer takes any parameters. Those parameters are now handled using
configuration options instead.

`ServiceSet` now enables configuration to set the root URL, toggle which endpoints
are exposed and set the internal error logger. These are passed in using a
`ServiceSetConfig` struct when the service is constructed; these configuration
options are not modifiable at runtime.

`Tileset` instances are now created individually from a set of source `mbtiles`
files, instead of generated within `ServiceSet` from a directory. This provides
more granular control over assigning IDs to tilesets as well as creating,
updating, or deleting `Tileset` instances. You must generate unique IDs for
tilesets before adding to the `ServiceSet`; you can use
`handlers.SHA1ID(filename)` to generate a unique SHA1 ID of the service based on
its full filename path, or `handlers.RelativePathID(filename, tilePath)` to
generate the ID from its path and filename within the tile directory `tilePath`.

HMAC authorization has been refactored into middleware external to the Go API.
It now is instantiated as middleware in `main.go`; this provides better
separation of concerns between the server (`main.go`) and the Go API. The API
for interacting with HMAC authorization from the CLI or endpoints remains the
same.

Most of the updates are demonstrated in `main.go`.

### Command-line interface

-   added support for automatically generating unique tileset IDs using `--generate-ids` option
-   added ability to toggle off non-tile endpoints:

    -   `--disable-preview`: disables the map preview, enabled by default.
    -   `--disable-svc-list`: disables the list of map services, enabled by default
    -   `--disable-tilejson`: disables the TileJSON endpoint for each tile service
    -   `--tiles-only`: shortcut that disables preview, service list, and TileJSON endpoints

-   moved static assets for map preview that were originally served on `/static`
    endpoint to `/services/<tileset_id>/map/static` so that this endpoint is
    disabled when preview is disabled via `--disable-preview`.

### Go API

-   added `ServiceSetConfig` for configuration options for `ServiceSet` instances
-   added `ServiceSet.AddTileset()`, `ServiceSet.UpdateTileset()`,
    `ServiceSet.RemoveTileset()`, and `ServiceSet.HasTileset()` functions.
    WARNING: these functions are not yet thread-safe.

#### Command-line interface:

-   ArcGIS endpoints are now opt-in via `--enable-arcgis` option (disabled by default)
-   `--path` option has been renamed to `--root-url` for clarity (env var is now `ROOT_URL`)
-   `--enable-reload` has been renamed to `--enable-reload-signal`

#### Handlers API

-   `ServiceSet.Handler` parameters have been replaced with `ServiceSetConfig`
    passed to `handlers.New()` instead.
-   removed `handlers.NewFromBaseDir()`, replaced with `handlers.New()` and calling
    `ServiceSet.AddTileset()` for each `Tileset` to register.
-   removed `ServiceSet.AddDBOnPath()`; this is replaced by calling
    `ServiceSet.AddTileset()` for each `Tileset` to register.

@nikmolnar this renames `--enable-reload` to `--enable-reload-signal` without deprecation period (the CHANGELOG should suffice to warn for deprecated uncommon command line options / name changes).  Any concerns with that?

@nikmolnar this changeset also moves HMAC auth middleware from inside every handler, and consolidates into a middleware layer that is external to them; it wraps the base handler within the chain of `echo` middleware at the server rather than handler level.  This was to get us better separation of concerns; the _server_ needs to manage auth via command line options, but the individual handlers should not need to be concerned with auth.  From my testing, HMAC auth continued to work properly as expected.

### CODE REVIEW

**Comment by brendan-ward** [comment]
@asmyasnikov would you mind testing this branch as a replacement to #99 ?  It should achieve the same functionality, but with quite different internal flow of data.

**Comment by asmyasnikov** [comment]
I will try it on next week

**Comment by asmyasnikov** [comment]
I was tested this branch (generate_ids) with functional interesting for me: multiple paths, generate ids. It works fine. 
P.S. I'm not use TLS and other features.

**Comment by sikmir** [comment]
@brendan-ward Do you plan to make a release? I think this PR brings great improvements and it works quite stable.

**Comment by morandd** [comment]
very minor issue: the README at the homepage documents the new "--enable-reload-signal" but when Joe User (ie, me) downloads the latest release we must actually use the old "--enable-reload". I guess this will be automatically solved by the next Release.
thanks for this excellent utility! So. good.

**Pull request merged**
